name: 🐧 Linux build

on: [push, pull_request, workflow_dispatch]

env:
  BUILD_TYPE: Release # Change build type here.

jobs:
  build_gcc:
    name: GCC build
    runs-on: ubuntu-18.04 # Update Ubuntu version here.

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Conan
      shell: bash
      run: |
        sudo pip install conan

    - name: Build
      shell: bash
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER="/usr/bin/g++" -DCMAKE_C_COMPILER="/usr/bin/gcc"
        cmake --build . --config $BUILD_TYPE

    - name: Tests
      shell: bash
      run: |
        cd build/tests/
        ctest --verbose

  build_clang:
    name: Clang build
    runs-on: ubuntu-18.04 # Update Ubuntu version here.

    steps:
      - uses: actions/checkout@v2

      - name: Install Conan
        shell: bash
        run: |
          sudo pip install conan

      - name: Build
        shell: bash
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER="/usr/bin/clang++" -DCMAKE_C_COMPILER="/usr/bin/clang"
          cmake --build . --config $BUILD_TYPE

      - name: Tests
        shell: bash
        run: |
          cd build/tests/
          ctest --verbose
