name: 📊 Sanitizers check

on: [push, pull_request, workflow_dispatch]

env:
  BUILD_TYPE: Debug # Change build type here.

jobs:
  address_sanitizer:
    name: 📊 Address sanitizer
    runs-on: ubuntu-20.04 # Update Ubuntu version here.

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      shell: bash
      run: |
        sudo pip install conan

    - name: Run address sanitizer
      shell: bash
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DACTIVATE_SANITIZERS="Address" -DCMAKE_CXX_COMPILER="/usr/bin/clang++" -DCMAKE_C_COMPILER="/usr/bin/clang"
        cmake --build . --config $BUILD_TYPE
        cd tests
        ctest --verbose

  thread_sanitizer:
    name: 📊 Thread sanitizer
    runs-on: ubuntu-20.04 # Update Ubuntu version here.

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      shell: bash
      run: |
        sudo pip install conan

    - name: Run thread sanitizer
      shell: bash
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DACTIVATE_SANITIZERS="Thread" -DCMAKE_CXX_COMPILER="/usr/bin/clang++" -DCMAKE_C_COMPILER="/usr/bin/clang"
        cmake --build . --config $BUILD_TYPE
        cd tests
        ctest --verbose

  undefined_sanitizer:
    name: 📊 Undefined sanitizer
    runs-on: ubuntu-20.04 # Update Ubuntu version here.

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      shell: bash
      run: |
        sudo pip install conan

    - name: Run undefined sanitizer
      shell: bash
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DACTIVATE_SANITIZERS="Undefined" -DCMAKE_CXX_COMPILER="/usr/bin/clang++" -DCMAKE_C_COMPILER="/usr/bin/clang"
        cmake --build . --config $BUILD_TYPE
        cd tests
        ctest --verbose

  leak_sanitizer:
    name: 📊 Leak sanitizer
    runs-on: ubuntu-20.04 # Update Ubuntu version here.

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      shell: bash
      run: |
        sudo pip install conan

    - name: Run leak sanitizer
      shell: bash
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DACTIVATE_SANITIZERS="Leak" -DCMAKE_CXX_COMPILER="/usr/bin/clang++" -DCMAKE_C_COMPILER="/usr/bin/clang"
        cmake --build . --config $BUILD_TYPE
        cd tests
        ctest --verbose

  memory_sanitizer:
    name: 📊 Memory sanitizer
    runs-on: ubuntu-20.04 # Update Ubuntu version here.

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      shell: bash
      run: |
        sudo pip install conan

    - name: Run memory sanitizer
      shell: bash
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DACTIVATE_SANITIZERS="Memory" -DCMAKE_CXX_COMPILER="/usr/bin/clang++" -DCMAKE_C_COMPILER="/usr/bin/clang"
        cmake --build . --config $BUILD_TYPE
        cd tests
        ctest --verbose
