name: 📊 CppCheck check

on: [push, pull_request, workflow_dispatch]

env:
  BUILD_TYPE: Debug # Change build type here.

jobs:
  build:
    runs-on: ubuntu-20.04 # Update Ubuntu version here.

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      shell: bash
      run: |
        sudo pip install conan

    - name: Install cppcheck
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Run cppcheck
      shell: bash
      run: |
        cd build
        cmake --build . --config $BUILD_TYPE --target CppCheck
